services:
  - type: web
    name: cbti-beer-test
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: ADMIN_TOKEN
        value: cbti-admin-2026
      - key: DATA_DIR
        value: /app/data
